@host=http://localhost:8080

###Create Employee
Post {{host}}/api/employee HTTP/1.1
Content-Type: application/json

{
"firstName": "Rohit",
"lastName": "Sharma",
"gender": "MALE",
"birthDate": "2000-12-25",
"hireDate": "2021-06-01",
"departmentId": 3
}

###List All Employees
GET {{host}}/api/employee HTTP/1.1

###List All Employees witrh Department Info
GET {{host}}/api/employee/with-department HTTP/1.1


###Get Employee by ID
GET {{host}}/api/employee/1 HTTP/1.1


###Delete by ID
DELETE {{host}}/api/employee/1 HTTP/1.1