apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-server
  template:
    metadata:
      labels:
        app: configuration-server
    spec:
      containers:
        - name: configuration-server
          image: jitendra111/configuration-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SERVER_PORT
              value: "8888"
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-server
spec:
  selector:
    app: configuration-server
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  type: ClusterIP
